version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11  # For Maven
      nodejs: 18       # For Serverless Framework
    commands:
      - echo "Installing Serverless..."
      - npm install -g serverless@^3 # Install Serverless v3

  build:
    commands:
      - echo "Building Java project with Maven..."
      - mvn package  # This builds your .jar file

  post_build:
    commands:
      - echo "Deploying with Serverless..."
      - serverless deploy